/**
 * Finds the difference between two strings. The first string is a random series of
 * characters of undetermined length. The second string is generated by shuffling the first 
 * string and add one more letter at a random position.
 * The object of the function is to find the letter that was added.
**/
class Solution {
    public char findTheDifference(String s, String t) {
        char[] charA = s.toCharArray();
        int[] charCount = new int[26];
        
        for (char c : charA) {
            charCount[c - 'a']++;
        }
        
        char[] charB = t.toCharArray();
        for (char c : charB) {
            charCount[c - 'a']++;
        }
        
        for (int i = 0; i < 26; i++) {
            if (charCount[i] % 2 == 1) {
                return (char)(i + 'a');
            }
        }
        
        return '1';
    }
}